# Generated by Django 5.2 on 2025-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_by_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Done'), (4, 'Overdue')]),
        ),
    ]
